set_max_delay -from [get_cells {peripherals/devinfo/sync_die_serial/sync_ack/sync/dout0_reg peripherals/devinfo/sync_die_serial/sync_en/sync/dout0_reg peripherals/devinfo/sync_idcode/sync_ack/sync/dout0_reg peripherals/devinfo/sync_idcode/sync_en/sync/dout0_reg}] -to [get_cells {extbridge/uartbridge/uart/sync_rx/dout1_reg peripherals/devinfo/sync_die_serial/sync_ack/sync/dout1_reg peripherals/devinfo/sync_die_serial/sync_en/sync/dout1_reg peripherals/devinfo/sync_idcode/sync_ack/sync/dout1_reg peripherals/devinfo/sync_idcode/sync_en/sync/dout1_reg}] 5.000
########################################################################################################################
# IO standard and pinning constraints

set_property IOSTANDARD LVCMOS33 [get_ports {clip_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clip_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clip_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {clip_out[0]}]
set_property DRIVE 4 [get_ports {clip_out[3]}]
set_property DRIVE 4 [get_ports {clip_out[2]}]
set_property DRIVE 4 [get_ports {clip_out[1]}]
set_property DRIVE 4 [get_ports {clip_out[0]}]
set_property PACKAGE_PIN J22 [get_ports {clip_out[3]}]
set_property PACKAGE_PIN J21 [get_ports {clip_out[2]}]
set_property PACKAGE_PIN H22 [get_ports {clip_out[1]}]
set_property PACKAGE_PIN G20 [get_ports {clip_out[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {coax_out[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {coax_out[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {coax_out[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {coax_out[0]}]
set_property SLEW FAST [get_ports {coax_out[3]}]
set_property SLEW FAST [get_ports {coax_out[2]}]
set_property SLEW FAST [get_ports {coax_out[1]}]
set_property SLEW FAST [get_ports {coax_out[0]}]
set_property PACKAGE_PIN V2 [get_ports {coax_out[3]}]
set_property PACKAGE_PIN U1 [get_ports {coax_out[2]}]
set_property PACKAGE_PIN T1 [get_ports {coax_out[1]}]
set_property PACKAGE_PIN R2 [get_ports {coax_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_dq[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_dq[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_dq[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {flash_dq[0]}]
set_property PACKAGE_PIN R21 [get_ports {flash_dq[3]}]
set_property PACKAGE_PIN P21 [get_ports {flash_dq[2]}]
set_property PACKAGE_PIN R22 [get_ports {flash_dq[1]}]
set_property PACKAGE_PIN P22 [get_ports {flash_dq[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_a_hi[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_a_hi[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_a_hi[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_a_hi[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_a_hi[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_a_hi[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_a_hi[0]}]
set_property PACKAGE_PIN AA20 [get_ports {fmc_a_hi[0]}]
set_property PACKAGE_PIN AA18 [get_ports {fmc_a_hi[1]}]
set_property PACKAGE_PIN AB18 [get_ports {fmc_a_hi[2]}]
set_property PACKAGE_PIN N15 [get_ports {fmc_a_hi[3]}]
set_property PACKAGE_PIN N14 [get_ports {fmc_a_hi[4]}]
set_property PACKAGE_PIN N13 [get_ports {fmc_a_hi[5]}]
set_property PACKAGE_PIN P15 [get_ports {fmc_a_hi[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_ad[0]}]
set_property DRIVE 4 [get_ports {fmc_ad[15]}]
set_property DRIVE 4 [get_ports {fmc_ad[14]}]
set_property DRIVE 4 [get_ports {fmc_ad[13]}]
set_property DRIVE 4 [get_ports {fmc_ad[12]}]
set_property DRIVE 4 [get_ports {fmc_ad[11]}]
set_property DRIVE 4 [get_ports {fmc_ad[10]}]
set_property DRIVE 4 [get_ports {fmc_ad[9]}]
set_property DRIVE 4 [get_ports {fmc_ad[8]}]
set_property DRIVE 4 [get_ports {fmc_ad[7]}]
set_property DRIVE 4 [get_ports {fmc_ad[6]}]
set_property DRIVE 4 [get_ports {fmc_ad[5]}]
set_property DRIVE 4 [get_ports {fmc_ad[4]}]
set_property DRIVE 4 [get_ports {fmc_ad[3]}]
set_property DRIVE 4 [get_ports {fmc_ad[2]}]
set_property DRIVE 4 [get_ports {fmc_ad[1]}]
set_property DRIVE 4 [get_ports {fmc_ad[0]}]
set_property PACKAGE_PIN W17 [get_ports {fmc_ad[0]}]
set_property PACKAGE_PIN AA21 [get_ports {fmc_ad[1]}]
set_property PACKAGE_PIN U20 [get_ports {fmc_ad[2]}]
set_property PACKAGE_PIN P14 [get_ports {fmc_ad[3]}]
set_property PACKAGE_PIN W21 [get_ports {fmc_ad[4]}]
set_property PACKAGE_PIN V22 [get_ports {fmc_ad[5]}]
set_property PACKAGE_PIN P17 [get_ports {fmc_ad[6]}]
set_property PACKAGE_PIN N17 [get_ports {fmc_ad[7]}]
set_property PACKAGE_PIN R18 [get_ports {fmc_ad[8]}]
set_property PACKAGE_PIN U21 [get_ports {fmc_ad[9]}]
set_property PACKAGE_PIN W22 [get_ports {fmc_ad[10]}]
set_property PACKAGE_PIN Y21 [get_ports {fmc_ad[11]}]
set_property PACKAGE_PIN Y22 [get_ports {fmc_ad[12]}]
set_property PACKAGE_PIN AB21 [get_ports {fmc_ad[13]}]
set_property PACKAGE_PIN AB20 [get_ports {fmc_ad[14]}]
set_property PACKAGE_PIN AB22 [get_ports {fmc_ad[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_nbl[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fmc_nbl[0]}]
set_property PACKAGE_PIN R17 [get_ports {fmc_nbl[1]}]
set_property PACKAGE_PIN U18 [get_ports {fmc_nbl[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN E22 [get_ports {led[3]}]
set_property PACKAGE_PIN D22 [get_ports {led[2]}]
set_property PACKAGE_PIN C22 [get_ports {led[1]}]
set_property PACKAGE_PIN B22 [get_ports {led[0]}]
set_property SLEW SLOW [get_ports {led[3]}]
set_property SLEW SLOW [get_ports {led[2]}]
set_property SLEW SLOW [get_ports {led[1]}]
set_property SLEW SLOW [get_ports {led[0]}]
set_property DRIVE 4 [get_ports {led[3]}]
set_property DRIVE 4 [get_ports {led[2]}]
set_property DRIVE 4 [get_ports {led[1]}]
set_property DRIVE 4 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pmod_io[0]}]
set_property PACKAGE_PIN A15 [get_ports {pmod_io[6]}]
set_property PACKAGE_PIN A14 [get_ports {pmod_io[5]}]
set_property PACKAGE_PIN A13 [get_ports {pmod_io[4]}]
set_property PACKAGE_PIN B16 [get_ports {pmod_io[3]}]
set_property PACKAGE_PIN B15 [get_ports {pmod_io[2]}]
set_property PACKAGE_PIN C14 [get_ports {pmod_io[1]}]
set_property PACKAGE_PIN B13 [get_ports {pmod_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_25mhz]
set_property PACKAGE_PIN W19 [get_ports clk_25mhz]
set_property PACKAGE_PIN T19 [get_ports flash_cs_n]
set_property IOSTANDARD LVCMOS33 [get_ports flash_cs_n]
set_property PACKAGE_PIN Y18 [get_ports fmc_clk]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_clk]
set_property PACKAGE_PIN P16 [get_ports fmc_ne1]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_ne1]
set_property PACKAGE_PIN T21 [get_ports fmc_ne2]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_ne2]
set_property PACKAGE_PIN T18 [get_ports fmc_ne3]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_ne3]
set_property PACKAGE_PIN R14 [get_ports fmc_ne4]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_ne4]
set_property PACKAGE_PIN V20 [get_ports fmc_nl_nadv]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_nl_nadv]
set_property PACKAGE_PIN U17 [get_ports fmc_noe]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_noe]
set_property PACKAGE_PIN V17 [get_ports fmc_nwait]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_nwait]
set_property PACKAGE_PIN R16 [get_ports fmc_nwe]
set_property IOSTANDARD LVCMOS33 [get_ports fmc_nwe]
set_property PACKAGE_PIN B21 [get_ports led_ctrl]
set_property IOSTANDARD LVCMOS33 [get_ports led_ctrl]
set_property DRIVE 4 [get_ports led_ctrl]
set_property SLEW SLOW [get_ports led_ctrl]
set_property PACKAGE_PIN R19 [get_ports pam3_tx_n]
set_property IOSTANDARD LVCMOS33 [get_ports pam3_tx_n]
set_property SLEW SLOW [get_ports pam3_tx_n]
set_property PACKAGE_PIN P19 [get_ports pam3_tx_p]
set_property IOSTANDARD LVCMOS33 [get_ports pam3_tx_p]
set_property SLEW SLOW [get_ports pam3_tx_p]
set_property PACKAGE_PIN A18 [get_ports uart_cts_n]
set_property PACKAGE_PIN A16 [get_ports {pmod_io[7]}]
set_property PACKAGE_PIN A21 [get_ports uart_rts_n]
set_property IOSTANDARD LVCMOS33 [get_ports uart_cts_n]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rts_n]
set_property PACKAGE_PIN A20 [get_ports uart_rx]
set_property PACKAGE_PIN A19 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property DRIVE 4 [get_ports uart_tx]
set_property SLEW SLOW [get_ports uart_tx]
set_property DRIVE 4 [get_ports uart_rts_n]
set_property SLEW SLOW [get_ports uart_rts_n]

set_property PACKAGE_PIN F6 [get_ports gtp_ref_p]

set_property PULLTYPE PULLUP [get_ports fmc_ne1]
set_property PULLTYPE PULLUP [get_ports fmc_ne2]
set_property PULLTYPE PULLUP [get_ports fmc_ne3]
set_property PULLTYPE PULLUP [get_ports fmc_ne4]
set_property PULLTYPE PULLUP [get_ports fmc_noe]
set_property PULLTYPE PULLUP [get_ports fmc_nwe]

set_property PULLTYPE PULLDOWN [get_ports {fmc_a_hi[6]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_a_hi[5]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_a_hi[4]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_a_hi[3]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_a_hi[2]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_a_hi[1]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_a_hi[0]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_ad[15]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_ad[14]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_ad[13]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_ad[12]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_ad[11]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_ad[10]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_ad[9]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_ad[8]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_ad[7]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_ad[6]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_ad[5]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_ad[4]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_ad[3]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_ad[2]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_ad[1]}]
set_property PULLTYPE PULLDOWN [get_ports {fmc_ad[0]}]

########################################################################################################################
# Input clocks

create_clock -period 40.000 -name clk_25mhz -waveform {0.000 20.000} [get_ports clk_25mhz]
create_clock -period 6.667 -name fmc_clk -waveform {0.000 3.334} [get_ports fmc_clk]

########################################################################################################################
# CDC

# slow clock only used for getting DNA etc
set_false_path -from [get_clocks clk_50mhz_raw] -to [get_clocks pclk_raw]
set_clock_groups -asynchronous -group [get_clocks pclk_raw] -group [get_clocks clk_50mhz_raw]

# Synchronizer max delays: 5 ns (200 MHz) is << 1 cycle of both clocks
set_max_delay -datapath_only -from [get_cells -hierarchical -filter { NAME =~  "*sync*" && NAME =~  "*a_ff*" }] -to [get_cells -hierarchical -filter { NAME =~  "*sync*" && NAME =~  "*reg_b*" }] 5.000
set_max_delay -from [get_cells -hierarchical -filter { NAME =~  "*sync*" && NAME =~  "*dout0_reg*" }] -to [get_cells -hierarchical -filter { NAME =~  "*sync*" && NAME =~  "*dout1_reg*" }] 5.000

set _xlnx_shared_i0 [get_cells -hierarchical -filter { NAME =~  "*p*_reg*" }]
set_max_delay -datapath_only -from [get_cells -hierarchical -filter { NAME =~  "*sync_apb*" && NAME =~  "*upstream*" }] -to $_xlnx_shared_i0 5.000
set _xlnx_shared_i1 [get_cells -hierarchical -filter { NAME =~  "*sync_apb*" && NAME =~ "*downstream*" }]
set_max_delay -datapath_only -from $_xlnx_shared_i0 -to $_xlnx_shared_i1 5.000

set_max_delay -datapath_only -from [get_cells -hierarchical -filter { NAME =~ "*rst_n_reg*" }] -to [get_cells -hierarchical -filter { NAME =~  "*sync_rst*" && NAME =~ "*_reg*" }] 5.000

# APB clock domain crossings: 5 ns (200 MHz) is << 1 cycle of both clocks

########################################################################################################################
# Put the timestamp in the bitstream USERCODE

set_property BITSTREAM.CONFIG.USR_ACCESS TIMESTAMP [current_design]

########################################################################################################################
# Bitstream generation settings

set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

########################################################################################################################
# Vivado ILA


set_property DRIVE 4 [get_ports pam3_tx_n]
set_property DRIVE 4 [get_ports pam3_tx_p]





set_property DRIVE 16 [get_ports {coax_out[3]}]
set_property DRIVE 16 [get_ports {coax_out[2]}]
set_property DRIVE 16 [get_ports {coax_out[1]}]
set_property DRIVE 16 [get_ports {coax_out[0]}]


set_property PACKAGE_PIN B4 [get_ports gtp_tx0_p]
set_property PACKAGE_PIN D5 [get_ports gtp_tx1_p]

create_clock -period 6.400 -name gtp_ref_p -waveform {0.000 3.200} [get_ports gtp_ref_p]
